dictionaries = ["en_us", "de_ch"]
words = [
  # English
  "apa",
  "buenard",
  "deja",
  "hayagriva",
  "labelled",
  "libertinus",
  "noninteractive",
  "oncompile",
  "onnavigate",
  "onresetall",
  "recompiles",
  "reflows",
  "shiki",
  "showybox",
  "smallcaps",
  "srgb",
  "tinymist",
  "vedivad",

  # German
  "Kapiteltitel",
  "vorausgefülltem",
  "abbildungs",
  "aufzuwerten",
  "auseinanderfällt",
  "beschriftungsnamen",
  "brotdicke",
  "brotfallenlassen",
  "butterabschabens",
  "downloadseite",
  "einreichungsbereit",
  "erpresserbriefe",
  "flacht",
  "fliesstext",
  "fusszeilen",
  "grösse",
  "hinzuzeigen",
  "imaginieren",
  "klaustrophobisch",
  "klickbare",
  "klickbaren",
  "kommagetrennte",
  "mittl",
  "neudekorieren",
  "physikpaper",
  "platzhaltertext",
  "rendern",
  "rendert",
  "schichtdicke",
  "schriftgrösse",
  "seitengrösse",
  "serifenlose",
  "serifenschrift",
  "serifierte",
  "skripte",
  "skripting",
  "spass",
  "streichfähig",
  "stündigen",
  "syntaxhervorhebung",
  "usw",
  "verschachtelung",
  "weissbrot",
  "zeitschriftenartikel",
  "zeitschriftenvorlagen",
  "zitierstile",
  "überschriftsebene",
  "überschriftszeile",
]
include_paths = [
  "**/*.md",
  "**/*.svelte",
  "**/*.ts",
  "**/*.typ",
]
use_global = false
