dictionaries = ["en_us", "de_ch"]
words = [
  # English
  "apa",
  "buenard",
  "cva",
  "deja",
  "fsegurai",
  "hayagriva",
  "labelled",
  "libertinus",
  "noninteractive",
  "oklch",
  "oncompile",
  "onnavigate",
  "onresetall",
  "recompiles",
  "reflows",
  "shiki",
  "shiki's",
  "showybox",
  "smallcaps",
  "srgb",
  "tinymist",
  "vedivad",

  # German
  "vorausgefülltem",
  "Kapiteltitel",
]
include_paths = ["**/*.md", "**/*.typ", "**/*.ts", "**/*.tsx"]
use_global = false
